Add missing version number; also fix the check.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -23,8 +23,15 @@ jobs:
         with:
           path: ~/.asdf/plugins/php
       - name: require_php
-        run: echo "php" > ~/.tool-versions
+        run: echo "php 8.3" > ~/.tool-versions
       - name: install_php
         run: asdf install php
       - name: test_php
-        run: php -v
+        run: |
+          required_version="8.3" && \
+          actual_version=$(php -v | grep '(cli)' | awk '{ print $2 }' | sed 's/\.[0-9]*$//') && \
+          if [[ "$(printf '%s\n' "$required_version" "$actual_version" | sort -V | head -n1)" != "$required_version" ]]; then \
+            echo "PHP version $actual_version does not meet the required version $required_version" >&2 && exit 1; \
+          else \
+            echo "PHP version $actual_version meets the requirement"; \
+          fi
